#configuration-as-code:
#  deprecation: warn

jenkins:
  systemMessage: "Welcome to the demo setup for Jenkins Configuration as Code plugin. For more information look in the official repo with our demo setup: https://github.com/Praqma/praqma-jenkins-casc"
  agentProtocols:
    - "JNLP4-connect"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${adminuser:-demoAdmin}
         password: ${adminpw:-passw0rd}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer: "standard"
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: agent-private-key
              username: agentuser
              passphrase:  ""
              description: "ssh private key used to connect ssh slaves"
              privateKeySource:
                directEntry: # The key 'agent_private_key' resolved from a docker secret defined in docker-compose.yml
                  privateKey: ${agent_private_key}
jobs:
    - url: https://raw.githubusercontent.com/triologygmbh/jenkinsfile/1-declarative/Jenkinsfile
    - url: https://raw.githubusercontent.com/triologygmbh/jenkinsfile/1-declarative/Jenkinsfile

tool:
  git:
    installations:
      - name: Default
        home: "git"

security:
  remotingCLI:
    enabled: false

plugins:
 required:
   credentials: 2.1.17
#    git: 3.9.0
   ssh-slaves: 1.26
   warnings: 4.66
   matrix-auth: 2.3
   job-dsl: 1.68
   # For workfloat aggregator
   workflow-aggregator: 2.5
   timestamper: 1.8.9
   workflow-scm-step: 2.7
   maven-plugin: 2.17
   matrix-project: 1.7.1
   analysis-core: 1.94
   structs: 1.7
	 antisamy-markup-formatter: 1.5
